travis:
  secure:
    BINSTAR_TOKEN: N6s9ypjDIRtJSqmyzDnbO4jOCAj8ngNvnyQwucyelPCv3NZjxBd3fTMJwSERwISZIjfKtdZcpB4oI9DzbXLKD6R0bncwlCGjl9ELkQs77NMMe9n2qhebAFC6Yz5umB+7Ck0bfjn8om3hCkf5IG5M33ek7AuIhFZ2r3bQBNcClrw/JtU81GbjXNNJB9FGXXYOaUEk2lqSKmvRauein16i4CqkBcJDtRbl8CO/XBBslQ6Z+8RnzN78NoFSircHCdKJiY3QJeb9EG8A7QihrnOVWyP3oOEQxdFpp6bOD1dKu2EgbEpzAXVPnp69oXScu1ToFbCy+Gr7YUupa7kbYflEvBkYUcFi/kW/nIh0iVej3rD2aoHSdLLw9EBTIywwWWGl5Q9O9TodoriEg03X7HN66Xez2rAWC/G9RQXq1y2SRtPVcowjShkWcVhu+hjyiH8ypjWGo8oytMlWG3b9O5p4gyb/5mb7BLCI5rBEe1S59oh/IuRwOnJOdZlZzv5w2DGGFu+kGUR0pgWms+82jSuwnB/YvgUY/yg/IY5K0/iDAohyTlXL5PbyoaF0yjlrPJibw/dKeKjFH9CylRYThRyPoRYZbLvNVVSrONLj0CgzJSkMLZQ/efqMsFkHJeYDx8aReHXMFdCmFXHQCbF4FAh9G6ut/viIUcAVeMU7Tk/WtwU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
